### ISSUE TITLE
missing file AttributeTyper.h & .m

### ISSUE THREAD

**Issue by ChaosTong** [appwoodpecker/woodpecker-client#3]
missing file AttributeTyper.h & .m under path AppDevelopHelper/Components/Utils

**Comment by github-xiaogang** [comment]
em.. will fix it today, or you find the missing file in history commits here: [fix build problem](https://github.com/appwoodpecker/woodpecker-client/commit/ada7774db207b162e697adefbb98d7c93a2c1bf7)

**Comment by github-xiaogang** [comment]
if you just need the app not source file, there is a packaged app in the latest release tag, you can download it there.

**Comment by ChaosTong** [comment]
> if you just need the app not source file, there is a packaged app in the latest release tag, you can download it there.

yes, rm the ref, app works fine.
