### ISSUE TITLE
[bug]Non-public API usage - The app contains or inherits from non-public classes in Frameworks/WoodPeckeriOS.framework/WoodPeckeriOS: UNLegacyNotificationTrigger

### ISSUE THREAD

**Issue by robinmo** [appwoodpecker/woodpecker-client#5]
Could you help remove the non-public API usage.
The case is: 
Something we should integrate woodpecker into a testflight  app for testers.
Non-public API usage will be rejected by apple 

## issue details:

TMS-90338: Non-public API usage - The app contains or inherits from non-public classes in Frameworks/WoodPeckeriOS.framework/WoodPeckeriOS: UNLegacyNotificationTrigger . If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
Best regards,
The App Store Team

**Comment by github-xiaogang** [comment]
Okay, I will check it later.

**Comment by github-xiaogang** [comment]
Hi, legacy code has been already removed from the master branch, and the WoodpeckeriOS cocoapods will be update at this weekend.

**Comment by github-xiaogang** [comment]
Hi, WoodpeckeriOS pod 1.4.3 has just published, you could check it in a few hours.
